version: '3'

tasks:
  install:
    cmds:
      - composer install
      - npm install
      - cp .env.example .env
      - php artisan key:generate
      - php artisan storage:link
      - chmod -R 777 storage bootstrap/cache

  seed: #task seed で実行 ↓これでシーディングした時にDuplicateエラーが出ない
    cmds:
      - php artisan migrate:fresh --seed  